package io.arson.client.module;

import io.arson.client.settings.BooleanSetting;
import io.arson.client.settings.DoubleSetting;
import io.arson.client.settings.EnumSetting;
import net.minecraft.client.Minecraft;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.Map;

public final class ModuleManager {
    private final Map<String, Module> modules=new LinkedHashMap<>();
    public void register(Module module){if(modules.putIfAbsent(module.id(),module)!=null)throw new IllegalArgumentException("Duplicate module: "+module.id());}
    public void registerDefaults(){
        register(new ClientInfoModule());register(new SprintModule());register(new PerformanceModule());
        register(new ContainerESPModule());register(new EntityESPModule());register(new ItemESPModule());register(new EntityInfoModule());register(new EntityTracerModule());register(new BlockESPModule());
        register(new HudModule());register(new HudLayoutModule());register(new ArrayListModule());register(new CombatInfoModule());register(new TargetingModule());register(new AimAssistModule());register(new HoverTotemModule());register(new AutoTotemModule());register(new FriendsModule());register(new TotemPopCounterModule());register(new AttributeSwapModule());register(new PlayerInfoModule());register(new WorldInfoModule());
        register(new CombatStatusModule());register(new PlayerStatusModule());register(new MovementStatusModule());register(new RenderProfileModule());register(new WorldStatusModule());register(new StorageStatusModule());register(new UtilityStatusModule());
        register(GameStateModule.create());register(ScreenInfoModule.create());
    }
    public Module get(String id){return modules.get(id);} public Collection<Module> all(){return new ArrayList<>(modules.values());}
    public Collection<Module> organized(Module.Category category){ArrayList<Module> result=new ArrayList<>();for(Module module:modules.values())if(module.category()==category)result.add(module);result.sort(Comparator.comparing(Module::enabled).reversed().thenComparing(Module::name,String.CASE_INSENSITIVE_ORDER));return result;}
    public int categoryCount(Module.Category category){int count=0;for(Module module:modules.values())if(module.category()==category)count++;return count;}
    public int enabledCount(Module.Category category){int count=0;for(Module module:modules.values())if(module.category()==category&&module.enabled())count++;return count;}
    public int enabledCount(){int count=0;for(Module module:modules.values())if(module.enabled())count++;return count;} public void tick(Minecraft client){for(Module module:modules.values())module.tick(client);}
    public enum DisplayMode{COMPACT,DETAILED} public enum RenderMode{STANDARD,HIGH_CONTRAST,MINIMAL}
    private static final class ClientInfoModule extends Module{private ClientInfoModule(){super("client-info","Client Info",Category.MISC,"Shows client/version metadata used by the local HUD.");setting(new BooleanSetting("show-version","Show Version",true));}}
    private static final class SprintModule extends Module{private final BooleanSetting forwardOnly=setting(new BooleanSetting("forward-only","Forward Only",true));private SprintModule(){super("sprint","Sprint",Category.MOVEMENT,"Local sprint state helper; it only affects the local player's sprint flag while enabled.");}@Override protected void onTick(Minecraft client){if(client.player==null)return;if(forwardOnly.enabled()&&!client.options.keyUp.isDown())return;client.player.setSprinting(true);}}
    private static final class PerformanceModule extends Module{private final DoubleSetting tickBudget=setting(new DoubleSetting("tick-budget","Logic Budget",1.0,0.1,5.0,0.1));private PerformanceModule(){super("performance","Performance",Category.MISC,"Exposes a local logic-budget preference for diagnostics and presentation integrations.");}public double tickBudget(){return tickBudget.get();}}
    private static final class CombatStatusModule extends Module{private final EnumSetting<DisplayMode> mode=setting(new EnumSetting<>("mode","Display Mode",DisplayMode.COMPACT));private final DoubleSetting threshold=setting(new DoubleSetting("ready-threshold","Ready Threshold",0.90,0.0,1.0,0.05));private boolean ready;private CombatStatusModule(){super("combat-status","Combat Status",Category.COMBAT,"Reports local attack-cooldown readiness without issuing attacks.");mode.description("Choose the amount of local combat state shown by integrations.");threshold.description("Attack cooldown ratio considered ready.");}@Override protected void onTick(Minecraft client){ready=client.player!=null&&client.player.getAttackStrengthScale(0.0f)>=threshold.get();}public boolean ready(){return ready;}public DisplayMode mode(){return mode.get();}}
    private static final class PlayerStatusModule extends Module{private final EnumSetting<DisplayMode> mode=setting(new EnumSetting<>("mode","Display Mode",DisplayMode.COMPACT));private int hunger;private float health;private PlayerStatusModule(){super("player-status","Player Status",Category.PLAYER,"Tracks local health and hunger for HUD presentation.");mode.description("Choose compact or detailed local player telemetry.");}@Override protected void onTick(Minecraft client){if(client.player==null)return;hunger=client.player.getFoodData().getFoodLevel();health=client.player.getHealth();}public int hunger(){return hunger;}public float health(){return health;}public DisplayMode mode(){return mode.get();}}
    private static final class MovementStatusModule extends Module{private final EnumSetting<DisplayMode> mode=setting(new EnumSetting<>("mode","Display Mode",DisplayMode.COMPACT));private double horizontalSpeed;private MovementStatusModule(){super("movement-status","Movement Status",Category.MOVEMENT,"Reports local horizontal movement speed for HUDs and diagnostics.");}@Override protected void onTick(Minecraft client){if(client.player==null){horizontalSpeed=0;return;}var v=client.player.getDeltaMovement();horizontalSpeed=Math.sqrt(v.x*v.x+v.z*v.z);}public double horizontalSpeed(){return horizontalSpeed;}}
    private static final class RenderProfileModule extends Module{private final EnumSetting<RenderMode> mode=setting(new EnumSetting<>("mode","Render Profile",RenderMode.STANDARD));private RenderProfileModule(){super("render-profile","Render Profile",Category.RENDER,"Selects a local presentation profile consumed by visual integrations.");mode.description("Select a local visual profile; integrations may consume it.");}public RenderMode mode(){return mode.get();}}
    private static final class WorldStatusModule extends Module{private final EnumSetting<DisplayMode> mode=setting(new EnumSetting<>("mode","Display Mode",DisplayMode.COMPACT));private long time;private boolean raining;private WorldStatusModule(){super("world-status","World Status",Category.WORLD,"Reports local world time and weather state.");}@Override protected void onTick(Minecraft client){if(client.level==null){time=0;raining=false;return;}time=client.level.getDayTime();raining=client.level.isRaining();}public long time(){return time;}public boolean raining(){return raining;}}
    private static final class StorageStatusModule extends Module{private final BooleanSetting showScreenState=setting(new BooleanSetting("show-screen-state","Show Screen State",true));private boolean containerOpen;private StorageStatusModule(){super("storage-status","Storage Status",Category.MISC,"Reports whether a local container screen is currently open.");showScreenState.description("Track whether a local container screen is open.");}@Override protected void onTick(Minecraft client){containerOpen=showScreenState.enabled()&&client.screen instanceof net.minecraft.client.gui.screens.inventory.AbstractContainerScreen<?>;}public boolean containerOpen(){return containerOpen;}}
    private static final class UtilityStatusModule extends Module{private final EnumSetting<DisplayMode> mode=setting(new EnumSetting<>("mode","Display Mode",DisplayMode.COMPACT));private UtilityStatusModule(){super("utility-status","Utility Status",Category.MISC,"Local utility telemetry for compact HUD presentation.");}public DisplayMode mode(){return mode.get();}}
}
